plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: ["_backup", "CNAME", "LICENSE.md", "README.md", "Gemfile", "Gemfile.lock", ".htaccess"]

host: https://www.katringlinka.de
url: https://www.katringlinka.de

markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "Cultural Studies &amp; HCI &amp; Design"